---
- name: OpenSSL dhparam
  community.crypto.openssl_dhparam:
    path: "{{ nginx_dhparam_file }}"
    size: "{{ nginx_dhparam.bits | default(omit) }}"
  become: true
  when: nginx_dhparam_file is defined
  tags:
    - nginx
    - config
    - ssl
    - dhparam

- name: Conf.d presence
  ansible.builtin.template:
    src: "nginx-{{ item.name }}.j2"
    dest: "/etc/nginx/conf.d/{{ item.name }}"
    mode: 0644
  become: true
  loop: "{{ nginx_config_templates }}"
  notify: Reload nginx
  when:
    - nginx_config_templates is defined
    - item.state is not defined
      or item.state|lower == "present"
  tags:
    - nginx
    - config
    - conf.d

- name: Conf.d absence
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/{{ item.name }}"
    state: absent
  loop: "{{ nginx_config_templates }}"
  notify: Reload nginx
  when:
    - nginx_config_templates is defined
    - item.state is defined
    - item.state|lower == "absent"
  tags:
    - nginx
    - config
    - conf.d
