---
- name: openssl_dhparam
  community.crypto.openssl_dhparam:
    path: "{{ nginx_dhparam_file }}"
    size: "{{ nginx_dhparam.bits | default(omit) }}"
  become: true
  when: nginx_dhparam_file is defined
  tags:
    - nginx
    - config
    - ssl
    - dhparam

# deploy conf.d/* files from templates and vars
- name: conf.d
  ansible.builtin.template:
    src: "nginx-{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
    mode: 0644
  become: true
  loop: "{{ nginx_config_templates }}"
  notify: reload nginx
  when: nginx_config_templates is defined
  tags:
    - nginx
    - config
    - conf.d
