---
# tasks file for nginx
- name: Package
  ansible.builtin.package:
    name: "{{ nginx_packages | default('nginx') }}"
    update_cache: true
  become: true
  tags:
    - nginx
    - package

- name: Package
  ansible.builtin.package:
    name: python3-certbot-nginx
    update_cache: true
  when:
    - nginx_sites is defined
    - nginx_sites is search ("certname")
  tags:
    - nginx
    - package

- name: Facts
  ansible.builtin.service_facts:
  tags:
    - nginx
    - core
    - facts

- name: Configure
  ansible.builtin.import_tasks: configure.yml
  when:
    - "'nginx.service' in services"
  tags:
    - nginx
    - config

- name: Sites
  become: true
  when:
    - "'nginx.service' in services"
  block:
    - name: Template
      ansible.builtin.template:
        src: "{{ item.template | default('nginx-http-site.conf.j2') }}"
        dest: "/etc/nginx/sites-available/{{ item.name }}"
        mode: 0644
        backup: "{{ nginx_backup_vhosts | default(omit) }}"
      notify: Reload nginx
      loop: "{{ nginx_sites }}"
      when:
        - item.name != 'default'
        - item.available is not defined
          or item.available|lower in ['yes', 'true']
      tags:
        - nginx
        - vhost
        - template

    - name: Vhost absence
      ansible.builtin.file:
        path: "/etc/nginx/sites-available/{{ item.name }}"
        state: absent
      loop: "{{ nginx_sites }}"
      when:
        - item.available is defined
        - not item.available
      tags:
        - nginx
        - vhost
        - template

    - name: Link presence
      ansible.builtin.file:
        src: "../sites-available/{{ item.name }}"
        path:
          "/etc/nginx/sites-enabled/{{ item.index |
          default('') }}{{ item.name }}"
        state: link
      notify: Reload nginx
      loop: "{{ nginx_sites }}"
      when:
        - not ansible_check_mode
        - item.available is not defined
          or item.available
        - item.enabled is not defined
          or item.enabled
      tags:
        - nginx
        - vhost
        - link

    - name: Link absence
      ansible.builtin.file:
        path:
          "/etc/nginx/sites-enabled/{{ item.index |
          default('') }}{{ item.name }}"
        state: absent
      notify: Reload nginx
      loop: "{{ nginx_sites }}"
      when:
        ( item.enabled is defined and not item.enabled )
        or ( item.available is defined and not item.available )
      tags:
        - nginx
        - vhost
        - link
