---
# tasks file for nginx
- name: package
  package:
    name: "{{ nginx_package | default('nginx') }}"
  become: true
  tags:
    - nginx
    - package

- name: service_facts
  ansible.builtin.service_facts:
  tags:
    - nginx
    - facts

- name: openssl_dhparam
  openssl_dhparam:
    path: "{{ nginx_dhparam_file }}"
    size: "{{ nginx_dhparam.bits | default(omit) }}"
  become: true
  when: nginx_dhparam_file is defined
  tags:
    - nginx
    - ssl
    - dhparam

- name: vhost
  block:
    - name: "vhost"
      template:
        src: "{{ item.template | default('nginx-http-site.conf.j2') }}"
        dest: "/etc/nginx/sites-available/{{ item.name }}"
        mode: 0644
      notify: reload nginx
      loop: "{{ nginx_sites }}"
      when:
        - item.name != 'default'
        - item.available is not defined
          or item.available|lower in ['yes', 'true']
      tags:
        - nginx
        - vhost
        - template

    - name: "vhost absence"
      file:
        path: "/etc/nginx/sites-available/{{ item.name }}"
        state: absent
      loop: "{{ nginx_sites }}"
      when:
        - item.available is defined
        - item.available|lower in ['no', 'false']
      tags:
        - nginx
        - vhost
        - template

    - name: "link presence"
      file:
        src: "../sites-available/{{ item.name }}"
        path:
          "/etc/nginx/sites-enabled/{{ item.index |
          default('') }}{{ item.name }}"
        state: link
      notify: reload nginx
      loop: "{{ nginx_sites }}"
      when:
        - not ansible_check_mode
        - item.available is not defined
          or item.available|lower in ['yes', 'true']
        - item.enabled is not defined
          or item.enabled|lower in ['yes', 'true']
      tags:
        - nginx
        - vhost
        - link

    - name: "link absence"
      file:
        path:
          "/etc/nginx/sites-enabled/{{ item.index |
          default('') }}{{ item.name }}"
        state: absent
      notify: reload nginx
      loop: "{{ nginx_sites }}"
      when:
        - item.enabled is defined
        - not item.enabled
      tags:
        - nginx
        - vhost
        - link

  become: true
  when:
    - "'nginx.service' in services"
