---
# tasks file for nginx
- name: "package"
  package:
    name: nginx
  become: true
  tags:
    - nginx
    - package

- name: "service"
  service:
    name: nginx
    enabled: true
  become: true
  tags:
    - nginx
    - service

- name: "openssl_dhparam"
  openssl_dhparam:
    path: '{{ nginx_dhparam_file }}'
    size: '{{ nginx_dhparam.bits }}'
  become: true
  tags:
    - nginx
    - dhparam

- name: "vhost"
  template:
    src: 'nginx-{{ item.template | default("generic") }}.conf.j2'
    dest: '/etc/nginx/sites-available/{{ item.name }}'
    mode: 0644
  loop: '{{ nginx_sites }}'
  when:
    - item.name != 'default'
    - item.available is not defined
      or item.available|lower in ['yes', 'true']
  become: true
  tags:
    - nginx
    - vhost
    - template

- name: "vhost absence"
  file:
    path: '/etc/nginx/sites-available/{{ item.name }}'
    state: absent
  loop: '{{ nginx_sites }}'
  when:
    - item.available is defined
    - item.available|lower in ['no', 'false']
  become: true
  tags:
    - nginx
    - vhost
    - template

- name: "link presence"
  file:
    src: '/etc/nginx/sites-available/{{ item.name }}'
    path: '/etc/nginx/sites-enabled/{{ item.index|default("") }}{{ item.name }}'
    state: 'link'
  notify: restart nginx
  loop: '{{ nginx_sites }}'
  when:
    - item.available is not defined
      or item.available|lower in ['yes', 'true']
    - item.enabled is not defined
      or item.enabled|lower in ['yes', 'true']
  become: true
  tags:
    - nginx
    - vhost
    - link

- name: "link absence"
  file:
    path: '/etc/nginx/sites-enabled/{{ item.index|default("") }}{{ item.name }}'
    state: absent
  notify: restart nginx
  loop: '{{ nginx_sites }}'
  when:
    - item.enabled is defined
    - item.enabled|lower in ['no', 'false']
  become: true
  tags:
    - nginx
    - vhost
    - link
...
