---
# handlers file for nginx
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when:
    - "'nginx.service' in services"

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when:
    - "'nginx.service' in services"
